/*
  Warnings:

  - The values [ARBEITSGRUPPE,PRAKTIKUM_MIT_INTEGRIERTEM_SEMINAR] on the enum `VeranstaltungsTyp` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "VeranstaltungsTyp_new" AS ENUM ('ABK_KURSE', 'ANLEITUNG', 'ARBEITSGEMEINSCHAFTEN', 'BEGLEITSEMINAR', 'BERUFSPRAKTISCHE_UEBUNG', 'BLOCKLEHRVERANSTALTUNG', 'BLOCKPRAKTIKUM', 'EDV_TUTORIEN', 'EINFUEHRUNGSKURS', 'EINFUEHRUNGSVORLESUNG', 'ERGAENZENDE_SPRACHLEHRVERANSTALTUNG', 'EXAMENSKOLLOQUIUM', 'EXKURSION', 'EXKURSION_PRAKTIKUM', 'FOERDERKURS', 'FORSCHUNGSKOLLOQUIUM', 'FORSCHUNGSSEMINAR', 'GELAENDEPRAKTIKUM', 'GELAENDEPRAKTIKUM_UND_SEMINAR', 'GELAENDEUEBUNG', 'GELAENDEUEBUNG_UND_SEMINAR', 'GROSSE_EXKURSION', 'GROSSVORLESUNG', 'GRUNDKURS', 'HALBTAGS_GANZTAGS_PRAKTIKUM', 'HAUPTSEMINAR', 'HAUPTSEMINAR_VORLESUNG_UEBUNG', 'INFOVERANSTALTUNG', 'INTEGRIERTE_VERANSTALTUNG', 'INTENSIVKURS', 'INTERAKTIVE_LEHRVERANSTALTUNG', 'KLEINE_EXKURSION', 'KOLLOQUIUM', 'KOMPAKTKURS', 'KURSPRAKTIKUM', 'LABORPRAKTIKUM', 'LEHRGANG', 'LEKTUEREKURS', 'LEKTUERESEMINAR', 'LESUNG', 'MITTELSEMINAR', 'MITTELSEMINAR_UEBUNG', 'MITTELSEMINAR_UEBUNG_VORLESUNG', 'MUSIKALISCHE_PRAXIS', 'OBERSEMINAR', 'ORIENTIERUNGSEINHEIT', 'PRAKTIKUM', 'PRAKTIKUM_MIT_SEMINAR', 'PRAKTIKUMSSEMINAR', 'PRAXISBEGLEITSEMINAR', 'PRAXISBEZOGENE_EINFUEHRUNG', 'PROJEKT', 'PROJEKT_SEMINAR', 'PROJEKT_I', 'PROJEKT_I_II', 'PROJEKT_II', 'PROJEKTSEMINAR', 'PROPAEDEUTIKUM', 'PROSEMINAR', 'PRUEFUNG', 'RINGVORLESUNG', 'SELBSTSTUDIUM', 'SEMINAR', 'SEMINAR_I', 'SEMINAR_IA', 'SEMINAR_IB', 'SEMINAR_II', 'SEMINAR_III', 'SEMINAR_EXKURSION', 'SEMINAR_UEBUNG', 'SEMINAR_UEBUNG_VORLESUNG', 'SEMINAR_VORLESUNG', 'SICHT_HOERTERMIN', 'SPORTKURS', 'SPRACHKURS', 'SPRACHLEHRVERANSTALTUNG', 'SPRACHLEHRVERANSTALTUNG_I', 'SPRACHLEHRVERANSTALTUNG_II', 'STILUEBUNG', 'STUDIE', 'TRANSLATORISCHE_LEHRVERANSTALTUNG', 'TRANSLATORISCHE_UEBUNG_I', 'TRANSLATORISCHE_UEBUNG_II', 'TUTORIUM', 'UEBUNG', 'UEBUNG_PRAKTIKUM', 'VERTIEFUNGSSEMINAR', 'VORLESUNG', 'VORLESUNG_SEMINAR', 'VORLESUNG_TUTORIUM', 'VORLESUNG_UEBUNG', 'VORLESUNG_SEMINAR_HAUPTSEMINAR', 'WISSENSCHAFTLICHER_GRUNDLAGENKURS', 'WISSENSCHAFTLICHES_PRAKTIKUM', 'WORKSHOP', 'UNDEFINED');
ALTER TABLE "Veranstaltung" ALTER COLUMN "typ" TYPE "VeranstaltungsTyp_new" USING ("typ"::text::"VeranstaltungsTyp_new");
ALTER TYPE "VeranstaltungsTyp" RENAME TO "VeranstaltungsTyp_old";
ALTER TYPE "VeranstaltungsTyp_new" RENAME TO "VeranstaltungsTyp";
DROP TYPE "public"."VeranstaltungsTyp_old";
COMMIT;
